#!/usr/bin/env python
from scanner import app
import sys

print "testing"

def start_flask():
    app.debug = False
    app.run(host='0.0.0.0')

if __name__ == '__main__':
    start_flask()

    from scanner.views import kill_scanner
    kill_scanner()

print "All done, closing..."
